Debug CI error
Signed-off-by: Xiake Sun <xiake.sun@amd.com>

diff --git a/.github/workflows/sglang_benchmark_workflow_mi350x.yaml b/.github/workflows/sglang_benchmark_workflow_mi350x.yaml
--- a/.github/workflows/sglang_benchmark_workflow_mi350x.yaml
+++ b/.github/workflows/sglang_benchmark_workflow_mi350x.yaml
@@ -199,13 +199,13 @@ jobs:
             exit 1
           fi
 
-      - name: Clean Up
-        if: always()
-        run: |
-          docker exec -u root sglang_test bash -c "rm -rf /sglang-checkout" 2>/dev/null || true
-          docker stop sglang_test 2>/dev/null || true
-          docker rm sglang_test 2>/dev/null || true
-          docker image rm sglang_test:ci 2>/dev/null || true
-          docker rmi -f $(docker images -f "dangling=true" -q) || true
-          docker image prune -f 2>/dev/null || true
-          docker builder prune -f 2>/dev/null || true
+      # - name: Clean Up
+      #   if: always()
+      #   run: |
+      #     docker exec -u root sglang_test bash -c "rm -rf /sglang-checkout" 2>/dev/null || true
+      #     docker stop sglang_test 2>/dev/null || true
+      #     docker rm sglang_test 2>/dev/null || true
+      #     docker image rm sglang_test:ci 2>/dev/null || true
+      #     docker rmi -f $(docker images -f "dangling=true" -q) || true
+      #     docker image prune -f 2>/dev/null || true
+      #     docker builder prune -f 2>/dev/null || true
